// Checks the TS ports of _z_score_q, pick_annotations, and
// overview_annotations against fixtures generated from the real Python
// implementation (see obs.test.ts for the shared fixture-loading rationale).

import { describe, expect, test } from 'bun:test';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { overviewAnnotations, pickAnnotations, zScoreQ } from './annotations';
import { ANN_BRAIN, ANN_SECRET, ANN_X } from './constants';
import type { Metadata } from '../onnx/metadata';

// src/pick/constants.py's ANN_* are terminal display strings (padded emoji);
// this file's ANN_* are semantic keys for the web UI. Map Python's raw
// strings to our keys so the fixture (generated by the Python CLI) can still
// check the underlying categorization logic is ported correctly.
const PY_ANNOTATION_TO_KEY: Record<string, string> = {
	' 🧠': ANN_BRAIN,
	' 🤫': ANN_SECRET,
	' ✗ ': ANN_X
};

function translate(annotations: Record<string, string>): Record<string, string> {
	return Object.fromEntries(
		Object.entries(annotations).map(([id, raw]) => {
			const key = PY_ANNOTATION_TO_KEY[raw];
			if (!key) throw new Error(`fixture used an unrecognized annotation string: ${JSON.stringify(raw)}`);
			return [id, key];
		})
	);
}

const STATIC_DIR = join(import.meta.dir, '../../../static');
const FIXTURE_PATH = join(import.meta.dir, '../../../tests/fixtures/logic_fixture.json');

function requireFile(path: string): Buffer {
	if (!existsSync(path)) {
		throw new Error(`logic fixture missing: ${path}\nRun \`just export-onnx\` from the repo root first.`);
	}
	return readFileSync(path);
}

interface ZScoreCase {
	q_values: number[];
	available_char_idxs: number[];
	z: number[];
}

interface AnnotationCase {
	event_id: number;
	scores: { id: number; score: number }[];
	annotations: Record<string, string>;
}

interface Fixture {
	z_score: ZScoreCase[];
	pick_annotations: AnnotationCase[];
	overview_annotations: AnnotationCase[];
}

const fixture: Fixture = JSON.parse(requireFile(FIXTURE_PATH).toString('utf-8'));
const metadata: Metadata = JSON.parse(requireFile(join(STATIC_DIR, 'data/metadata.json')).toString('utf-8'));

function eventById(id: number) {
	const e = metadata.events.find((ev) => ev.id === id);
	if (!e) throw new Error(`fixture references unknown event id ${id}`);
	return e;
}

describe('zScoreQ', () => {
	test('matches the Python (numpy, population std) reference', () => {
		expect(fixture.z_score.length).toBeGreaterThan(0);
		for (const c of fixture.z_score) {
			const z = zScoreQ(c.q_values, c.available_char_idxs);
			expect(z.length).toBe(c.z.length);
			for (let i = 0; i < z.length; i++) {
				expect(z[i]).toBeCloseTo(c.z[i], 8);
			}
		}
	});
});

describe('pickAnnotations', () => {
	test('matches the Python reference for every fixture case', () => {
		expect(fixture.pick_annotations.length).toBeGreaterThan(0);
		for (const c of fixture.pick_annotations) {
			const result = pickAnnotations(metadata, eventById(c.event_id), c.scores);
			const asObj = Object.fromEntries(Array.from(result.entries()).map(([k, v]) => [String(k), v]));
			expect(asObj).toEqual(translate(c.annotations));
		}
	});
});

describe('overviewAnnotations', () => {
	test('matches the Python reference for every fixture case', () => {
		expect(fixture.overview_annotations.length).toBeGreaterThan(0);
		for (const c of fixture.overview_annotations) {
			const result = overviewAnnotations(metadata, eventById(c.event_id), c.scores);
			const asObj = Object.fromEntries(Array.from(result.entries()).map(([k, v]) => [String(k), v]));
			expect(asObj).toEqual(translate(c.annotations));
		}
	});
});
