// Confirms the exported ONNX graphs (web/static/models/*.onnx) still produce
// the same numbers under onnxruntime-web (the runtime the browser app uses)
// as the real trained JAX models did at export time. Fixtures and the
// static/ artifacts are generated by `just export-onnx`
// (src/pick/export_onnx.py) — run it before `bun test` if either is missing.

import { describe, expect, test, beforeAll } from 'bun:test';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import type { InferenceSession } from 'onnxruntime-web';
import { createSession, runDraftQ, runTerminalPick6 } from './session';
import { charEncsRowForEvent, flattenCharMeta, type Manifest } from './manifest';

const STATIC_DIR = join(import.meta.dir, '../../../static');
const FIXTURE_PATH = join(import.meta.dir, '../../../tests/fixtures/onnx_fixture.json');

interface DraftQCase {
	event_idx: number;
	player_char_states: number[];
	turn_token: number;
	q_values: number[];
}

interface TerminalPick6Case {
	event_idx: number;
	mode_idx: number;
	team_a_chars: number[];
	team_a_meta: number[][];
	team_b_chars: number[];
	team_b_meta: number[][];
	logit: number;
}

interface Fixture {
	draft_q: DraftQCase[];
	terminal_pick6: TerminalPick6Case[];
}

function requireFile(path: string): Buffer {
	if (!existsSync(path)) {
		throw new Error(
			`onnx test fixture/artifact missing: ${path}\nRun \`just export-onnx\` from the repo root first.`
		);
	}
	return readFileSync(path);
}

const fixture: Fixture = JSON.parse(requireFile(FIXTURE_PATH).toString('utf-8'));
const manifest: Manifest = JSON.parse(
	requireFile(join(STATIC_DIR, 'data/manifest.json')).toString('utf-8')
);
const charEncsBytes = requireFile(join(STATIC_DIR, 'data/char_encs.bin'));
// Buffer.buffer may be a view into a larger pooled ArrayBuffer — slice explicitly.
const charEncsAll = new Float32Array(
	charEncsBytes.buffer,
	charEncsBytes.byteOffset,
	charEncsBytes.byteLength / Float32Array.BYTES_PER_ELEMENT
);

describe('draft_q.onnx', () => {
	let session: InferenceSession;

	beforeAll(async () => {
		session = await createSession(requireFile(join(STATIC_DIR, 'models/draft_q.onnx')));
	});

	test('matches the JAX reference for every fixture case', async () => {
		expect(fixture.draft_q.length).toBeGreaterThan(0);
		for (const c of fixture.draft_q) {
			const charEncsRow = charEncsRowForEvent(charEncsAll, manifest, c.event_idx);
			const q = await runDraftQ(
				session,
				charEncsRow,
				Int32Array.from(c.player_char_states),
				c.turn_token,
				manifest.n_chars,
				manifest.h_terminal
			);
			expect(q.length).toBe(manifest.n_chars);
			for (let i = 0; i < q.length; i++) {
				expect(q[i]).toBeCloseTo(c.q_values[i], 3);
			}
		}
	});
});

describe('terminal_pick6.onnx', () => {
	let session: InferenceSession;

	beforeAll(async () => {
		session = await createSession(requireFile(join(STATIC_DIR, 'models/terminal_pick6.onnx')));
	});

	test('matches the JAX reference for every fixture case', async () => {
		expect(fixture.terminal_pick6.length).toBeGreaterThan(0);
		for (const c of fixture.terminal_pick6) {
			const logit = await runTerminalPick6(
				session,
				c.event_idx,
				c.mode_idx,
				Int32Array.from(c.team_a_chars),
				flattenCharMeta(c.team_a_meta),
				Int32Array.from(c.team_b_chars),
				flattenCharMeta(c.team_b_meta)
			);
			expect(logit).toBeCloseTo(c.logit, 3);
		}
	});
});
